if(NOT DEFINED INK_TOKENIZER OR NOT DEFINED INK_TEST_DIRECTORY)
  message(FATAL_ERROR "Tokenizer executable and test directory are required")
endif()

file(MAKE_DIRECTORY "${INK_TEST_DIRECTORY}")
set(Input "${INK_TEST_DIRECTORY}/source.ink")
file(WRITE "${Input}" "var x = '\\U0001F600'; // ignored\r\nr\"a\\\"")
execute_process(COMMAND "${INK_TOKENIZER}" "${Input}" RESULT_VARIABLE Status OUTPUT_VARIABLE Output ERROR_VARIABLE Error)
if(NOT Status EQUAL 0 OR NOT Error STREQUAL "")
  message(FATAL_ERROR "Valid source failed: ${Status}: ${Error}")
endif()
foreach(Kind IN ITEMS KW_VAR IDENTIFIER ASSIGN CHAR_LITERAL SEMICOLON STRING_LITERAL END_OF_FILE)
  if(NOT Output MATCHES "${Kind} \\[")
    message(FATAL_ERROR "Missing ${Kind} in tokenizer output: ${Output}")
  endif()
endforeach()
if(Output MATCHES "COMMENT|LINE_BREAK|SPACES")
  message(FATAL_ERROR "Trivia must not be emitted: ${Output}")
endif()

file(WRITE "${Input}" "1_000")
execute_process(COMMAND "${INK_TOKENIZER}" "${Input}" RESULT_VARIABLE Status OUTPUT_VARIABLE Output ERROR_VARIABLE Error)
if(NOT Status EQUAL 1 OR NOT Error MATCHES "INK-T0008" OR NOT Error MATCHES "\\[0, 5\\)")
  message(FATAL_ERROR "Numeric error did not report its code and original byte range: ${Status}: ${Error}")
endif()
if(Output MATCHES "INTEGER_LITERAL|END_OF_FILE")
  message(FATAL_ERROR "Invalid number was split into valid tokens: ${Output}")
endif()

file(WRITE "${Input}" "")
execute_process(COMMAND "${INK_TOKENIZER}" "${Input}" RESULT_VARIABLE Status OUTPUT_VARIABLE Output ERROR_VARIABLE Error)
if(NOT Status EQUAL 0 OR NOT Output MATCHES "END_OF_FILE \\[0, 0\\)")
  message(FATAL_ERROR "Empty source did not produce EOF: ${Status}: ${Output}: ${Error}")
endif()
