if(NOT DEFINED INK_PARSER OR NOT DEFINED INK_TEST_DIRECTORY)
  message(FATAL_ERROR "Parser executable and test directory are required")
endif()
file(MAKE_DIRECTORY "${INK_TEST_DIRECTORY}")

# Each input is tested through both binary file input and redirected stdin.
# Exact string exit-code checks also reject crashes, signals and timeout messages.
function(check_source Name Source ExpectedStatus Diagnostic AstPattern)
  set(Input "${INK_TEST_DIRECTORY}/${Name}.ink")
  file(WRITE "${Input}" "${Source}")
  foreach(Mode IN ITEMS file stdin)
    if(Mode STREQUAL "file")
      execute_process(COMMAND "${INK_PARSER}" "${Input}" RESULT_VARIABLE Status OUTPUT_VARIABLE Output ERROR_VARIABLE Error TIMEOUT 10)
      set(FileOutput "${Output}")
    else()
      execute_process(COMMAND "${INK_PARSER}" "-" INPUT_FILE "${Input}" RESULT_VARIABLE Status OUTPUT_VARIABLE Output ERROR_VARIABLE Error TIMEOUT 10)
      if(NOT Output STREQUAL FileOutput)
        message(FATAL_ERROR "${Name}: file and stdin ASTs differ")
      endif()
    endif()
    if(NOT "${Status}" STREQUAL "${ExpectedStatus}")
      message(FATAL_ERROR "${Name} (${Mode}): expected exit ${ExpectedStatus}, got '${Status}': ${Error}")
    endif()
    if(ExpectedStatus STREQUAL "0")
      if(NOT Error STREQUAL "")
        message(FATAL_ERROR "${Name} (${Mode}): unexpected diagnostic: ${Error}")
      endif()
    elseif(NOT Error MATCHES "${Diagnostic}")
      message(FATAL_ERROR "${Name} (${Mode}): wrong diagnostic: ${Error}")
    endif()
    if(ExpectedStatus STREQUAL "3")
      if(NOT Error MATCHES "internal compiler error\\[${Diagnostic}\\]")
        message(FATAL_ERROR "${Name} (${Mode}): expected an ICE diagnostic: ${Error}")
      endif()
    elseif(Error MATCHES "internal compiler error")
      message(FATAL_ERROR "${Name} (${Mode}): unexpected ICE diagnostic: ${Error}")
    endif()
    if(Diagnostic MATCHES "^INK-T" AND Error MATCHES "INK-P")
      message(FATAL_ERROR "${Name} (${Mode}): lexical failure caused a parser diagnostic cascade: ${Error}")
    endif()
    if(NOT Output MATCHES "${AstPattern}")
      message(FATAL_ERROR "${Name} (${Mode}): expected AST pattern '${AstPattern}': ${Output}")
    endif()
  endforeach()
endfunction()

# Global encoding errors must be reported even inside comments and raw literals.
string(ASCII 192 175 OverlongSlash)
string(ASCII 237 160 128 Surrogate)
string(ASCII 244 144 128 128 AboveMaximum)
string(ASCII 240 159 152 Truncated)
string(ASCII 128 Continuation)
string(ASCII 255 254 Utf16Bom)
string(ASCII 239 187 191 Bom)
check_source(overlong_comment "var before = 1; /*${OverlongSlash}*/ var kept = 42;" 1 INK-T0001 "ModuleAST")
check_source(surrogate_raw_string "var text = r\"${Surrogate}\";" 1 INK-T0001 "ModuleAST")
check_source(above_maximum "var text = '${AboveMaximum}';" 1 INK-T0001 "ModuleAST")
check_source(truncated_eof "var kept = 42; //${Truncated}" 1 INK-T0001 "ModuleAST")
check_source(lone_continuation "${Continuation}" 1 INK-T0001 "ModuleAST")
check_source(utf16_bom "${Utf16Bom}" 1 INK-T0001 "ModuleAST")
check_source(utf8_bom "${Bom}var kept = 42;" 1 INK-T0002 "ModuleAST")

# Well-formed Unicode obeys the lexical rules both outside and inside content.
string(ASCII 226 128 139 ZeroWidthSpace)
string(ASCII 226 128 174 BidiOverride)
string(ASCII 226 128 168 LineSeparator)
string(ASCII 239 188 155 FullwidthSemicolon)
string(ASCII 204 129 CombiningAcute)
check_source(invisible_syntax "var before = 1; ${ZeroWidthSpace} var after = 2;" 1 INK-T0004 "Name=before")
check_source(bidi_syntax "var before = 1; ${BidiOverride}" 1 INK-T0004 "Name=before")
check_source(confusable_punctuation "var before = 1; ${FullwidthSemicolon}" 1 INK-T0004 "Name=before")
check_source(bidi_content "var text = \"${BidiOverride} } var hidden = 0;\"; var kept = 42;" 0 "" "Name=kept")
check_source(unicode_line_comment "var before = 1; //${LineSeparator} var hidden = 0;\nvar kept = 42;" 0 "" "Name=kept")
check_source(escaped_nul "var text = \"\\0\\u003B\\u007D\"; var kept = 42;" 0 "" "Name=kept")
check_source(escaped_surrogate "var text = \"\\uD800\";" 1 INK-T0016 "MissingExpr")

# Recovery must reach the sentinel declaration and must enforce default depth/diagnostic limits in the real CLI.
check_source(syntax_recovery "var x = f(1, , 3); var kept = 42;" 1 INK-P0002 "Name=kept")
check_source(missing_match_pattern "match(x) { A | => 1, _ => 2 }; var kept = 42;" 1 INK-P0003 "Name=kept")
check_source(unicode_recovery "var e${CombiningAcute} = 1\r\nvar kept = 42;" 1 INK-P0001 "Name=kept")
string(REPEAT "if(x) " 1024 DeepStatements)
check_source(deep_statements "${DeepStatements}return;" 3 INK-P0004 "MissingStmt")
string(REPEAT "(" 1024 DeepExpression)
check_source(deep_expression "var x = ${DeepExpression}x;" 3 INK-P0004 "MissingExpr")
string(REPEAT "var x = ; " 512 DiagnosticStorm)
check_source(diagnostic_storm "${DiagnosticStorm}var kept = 42;" 1 INK-P0002 "Name=kept")

# A successful invocation after all malformed files verifies that no shared external state was poisoned.
check_source(valid_after_attacks "func f(x: T): T { return x; } var kept = 42;" 0 "" "Name=kept")
