if(NOT DEFINED INK_PARSER OR NOT DEFINED INK_TEST_DIRECTORY)
  message(FATAL_ERROR "Parser executable and test directory are required")
endif()
file(MAKE_DIRECTORY "${INK_TEST_DIRECTORY}")
set(Input "${INK_TEST_DIRECTORY}/源码.ink")
file(WRITE "${Input}" "[tag] func f(x: int): int { return x + 1; }")
execute_process(COMMAND "${INK_PARSER}" "${Input}" RESULT_VARIABLE Status OUTPUT_VARIABLE Output ERROR_VARIABLE Error TIMEOUT 10)
if(NOT Status EQUAL 0 OR NOT Error STREQUAL "" OR NOT Output MATCHES "FunctionDecl" OR NOT Output MATCHES "BinaryExpr")
  message(FATAL_ERROR "Valid parser input failed: ${Status}: ${Output}: ${Error}")
endif()
execute_process(COMMAND "${INK_PARSER}" "-" INPUT_FILE "${Input}" RESULT_VARIABLE Status OUTPUT_VARIABLE StdinOutput ERROR_VARIABLE Error TIMEOUT 10)
if(NOT Status EQUAL 0 OR NOT StdinOutput STREQUAL Output)
  message(FATAL_ERROR "Standard input AST differs from file input: ${Status}: ${Error}")
endif()
file(WRITE "${Input}" "var a = 1\nvar b = f(2, , 4);")
execute_process(COMMAND "${INK_PARSER}" "${Input}" RESULT_VARIABLE Status OUTPUT_VARIABLE Output ERROR_VARIABLE Error TIMEOUT 10)
if(NOT Status EQUAL 1 OR NOT Error MATCHES "INK-P0001" OR NOT Error MATCHES "INK-P0002" OR NOT Output MATCHES "MissingExpr" OR NOT Output MATCHES "status=inserted")
  message(FATAL_ERROR "Recovery output or exit status is wrong: ${Status}: ${Output}: ${Error}")
endif()
file(WRITE "${Input}" "@")
execute_process(COMMAND "${INK_PARSER}" "${Input}" RESULT_VARIABLE Status OUTPUT_VARIABLE Output ERROR_VARIABLE Error TIMEOUT 10)
if(NOT Status EQUAL 1 OR NOT Error MATCHES "INK-T0004" OR Error MATCHES "INK-P")
  message(FATAL_ERROR "Lexical errors must not be re-diagnosed by the parser: ${Status}: ${Error}")
endif()
file(WRITE "${Input}" "")
execute_process(COMMAND "${INK_PARSER}" "${Input}" RESULT_VARIABLE Status OUTPUT_VARIABLE Output ERROR_VARIABLE Error TIMEOUT 10)
if(NOT Status EQUAL 0 OR NOT Output MATCHES "ModuleAST \\[0, 0\\)")
  message(FATAL_ERROR "Empty module failed: ${Status}: ${Output}: ${Error}")
endif()
execute_process(COMMAND "${INK_PARSER}" "${INK_TEST_DIRECTORY}/does-not-exist.ink" RESULT_VARIABLE Status OUTPUT_VARIABLE Output ERROR_VARIABLE Error TIMEOUT 10)
if(NOT Status EQUAL 2 OR NOT Error MATCHES "cannot open")
  message(FATAL_ERROR "Missing input should report invocation failure: ${Status}: ${Error}")
endif()
