if(NOT EXISTS "${INK_COMPILER}")
  message(FATAL_ERROR "inkc executable does not exist: ${INK_COMPILER}")
endif()

file(MAKE_DIRECTORY "${INK_TEST_DIRECTORY}")
set(InputPath "${INK_TEST_DIRECTORY}/test.i")
set(IrOutputPath "${INK_TEST_DIRECTORY}/test.ir")
file(WRITE "${InputPath}" "class")
file(REMOVE "${IrOutputPath}")

execute_process(COMMAND "${INK_COMPILER}" --help RESULT_VARIABLE HelpResult OUTPUT_VARIABLE HelpOutput ERROR_VARIABLE HelpError)
if(NOT HelpResult EQUAL 0 OR NOT "${HelpError}" STREQUAL "")
  message(FATAL_ERROR "help process contract failed: result=${HelpResult}\nstdout=${HelpOutput}\nstderr=${HelpError}")
endif()
string(FIND "${HelpOutput}" "inkc [OPTIONS]" HelpUsageOffset)
string(FIND "${HelpOutput}" "-i FILE REQUIRED" InputOptionOffset)
string(FIND "${HelpOutput}" "-oir FILE REQUIRED" IrOutputOptionOffset)
if(HelpUsageOffset EQUAL -1 OR InputOptionOffset EQUAL -1 OR IrOutputOptionOffset EQUAL -1)
  message(FATAL_ERROR "help output does not contain the compiler shell options: ${HelpOutput}")
endif()

execute_process(COMMAND "${INK_COMPILER}" -i "${InputPath}" -oir "${IrOutputPath}" RESULT_VARIABLE CompileResult OUTPUT_VARIABLE CompileOutput ERROR_VARIABLE CompileError)
if(NOT CompileResult EQUAL 0 OR NOT "${CompileOutput}" STREQUAL "" OR NOT "${CompileError}" STREQUAL "")
  message(FATAL_ERROR "compiler shell invocation failed: result=${CompileResult}\nstdout=${CompileOutput}\nstderr=${CompileError}")
endif()
if(EXISTS "${IrOutputPath}")
  message(FATAL_ERROR "compiler shell unexpectedly created an IR output file: ${IrOutputPath}")
endif()

execute_process(COMMAND "${INK_COMPILER}" -i "${InputPath}" RESULT_VARIABLE MissingOutputResult OUTPUT_VARIABLE MissingOutputOutput ERROR_VARIABLE MissingOutputError)
if(NOT MissingOutputResult EQUAL 2 OR NOT "${MissingOutputOutput}" STREQUAL "" OR "${MissingOutputError}" STREQUAL "")
  message(FATAL_ERROR "missing-output process contract failed: result=${MissingOutputResult}\nstdout=${MissingOutputOutput}\nstderr=${MissingOutputError}")
endif()
