if(NOT EXISTS "${INK_PARSER}")
  message(FATAL_ERROR "ink-parse executable does not exist: ${INK_PARSER}")
endif()

file(MAKE_DIRECTORY "${INK_TEST_DIRECTORY}")
set(ValidInput "${INK_TEST_DIRECTORY}/valid.ink")
set(SyntaxErrorInput "${INK_TEST_DIRECTORY}/syntax-error.ink")
set(LexicalErrorInput "${INK_TEST_DIRECTORY}/lexical-error.ink")
set(MissingInput "${INK_TEST_DIRECTORY}/missing.ink")
file(WRITE "${ValidInput}" "func main() { return; }")
file(WRITE "${SyntaxErrorInput}" ")")
file(WRITE "${LexicalErrorInput}" "\"")
file(REMOVE "${MissingInput}")

execute_process(COMMAND "${INK_PARSER}" --help RESULT_VARIABLE HelpResult OUTPUT_VARIABLE HelpOutput ERROR_VARIABLE HelpError)
if(NOT HelpResult EQUAL 0 OR NOT "${HelpError}" STREQUAL "")
  message(FATAL_ERROR "help process contract failed: result=${HelpResult}\nstdout=${HelpOutput}\nstderr=${HelpError}")
endif()
string(FIND "${HelpOutput}" "ink-parse [OPTIONS] [INPUT]" HelpUsageOffset)
if(HelpUsageOffset EQUAL -1)
  message(FATAL_ERROR "help output does not contain the public invocation spelling: ${HelpOutput}")
endif()

execute_process(COMMAND "${INK_PARSER}" INPUT_FILE "${ValidInput}" RESULT_VARIABLE StdinResult OUTPUT_VARIABLE StdinOutput ERROR_VARIABLE StdinError)
if(NOT StdinResult EQUAL 0 OR "${StdinOutput}" STREQUAL "" OR NOT "${StdinError}" STREQUAL "")
  message(FATAL_ERROR "stdin success contract failed: result=${StdinResult}\nstdout=${StdinOutput}\nstderr=${StdinError}")
endif()
string(FIND "${StdinOutput}" "Node " StdinNodeOffset)
string(FIND "${StdinOutput}" "Token " StdinTokenOffset)
if(StdinNodeOffset EQUAL -1 OR StdinTokenOffset EQUAL -1)
  message(FATAL_ERROR "successful parse did not print a recursive CST: ${StdinOutput}")
endif()

execute_process(COMMAND "${INK_PARSER}" "${SyntaxErrorInput}" RESULT_VARIABLE SyntaxErrorResult OUTPUT_VARIABLE SyntaxErrorOutput ERROR_VARIABLE SyntaxErrorError)
if(NOT SyntaxErrorResult EQUAL 1 OR "${SyntaxErrorOutput}" STREQUAL "" OR "${SyntaxErrorError}" STREQUAL "")
  message(FATAL_ERROR "syntax-error process contract failed: result=${SyntaxErrorResult}\nstdout=${SyntaxErrorOutput}\nstderr=${SyntaxErrorError}")
endif()
string(FIND "${SyntaxErrorOutput}" "Node " SyntaxNodeOffset)
string(FIND "${SyntaxErrorOutput}" "Token " SyntaxTokenOffset)
string(FIND "${SyntaxErrorOutput}" " Error " SyntaxErrorNodeOffset)
string(FIND "${SyntaxErrorError}" "error[INK-P" ParserDiagnosticOffset)
string(FIND "${SyntaxErrorError}" "INK-T" UnexpectedTokenizerDiagnosticOffset)
string(FIND "${SyntaxErrorError}" "${SyntaxErrorInput}:1:" SyntaxLocationOffset)
if(SyntaxNodeOffset EQUAL -1 OR SyntaxTokenOffset EQUAL -1 OR SyntaxErrorNodeOffset EQUAL -1 OR ParserDiagnosticOffset EQUAL -1 OR NOT UnexpectedTokenizerDiagnosticOffset EQUAL -1 OR SyntaxLocationOffset EQUAL -1)
  message(FATAL_ERROR "syntax-error output did not contain a recovered CST and only Parser diagnostics:\nstdout=${SyntaxErrorOutput}\nstderr=${SyntaxErrorError}")
endif()

execute_process(COMMAND "${INK_PARSER}" "${LexicalErrorInput}" RESULT_VARIABLE LexicalErrorResult OUTPUT_VARIABLE LexicalErrorOutput ERROR_VARIABLE LexicalErrorError)
if(NOT LexicalErrorResult EQUAL 1 OR NOT "${LexicalErrorOutput}" STREQUAL "" OR "${LexicalErrorError}" STREQUAL "")
  message(FATAL_ERROR "lexical-error process contract failed: result=${LexicalErrorResult}\nstdout=${LexicalErrorOutput}\nstderr=${LexicalErrorError}")
endif()
string(FIND "${LexicalErrorError}" "error[INK-T" TokenizerDiagnosticOffset)
string(FIND "${LexicalErrorError}" "INK-P" UnexpectedParserDiagnosticOffset)
string(FIND "${LexicalErrorError}" "${LexicalErrorInput}:1:" LexicalLocationOffset)
if(TokenizerDiagnosticOffset EQUAL -1 OR NOT UnexpectedParserDiagnosticOffset EQUAL -1 OR LexicalLocationOffset EQUAL -1)
  message(FATAL_ERROR "lexical failure did not stop before CST parsing or emitted non-Tokenizer diagnostics: ${LexicalErrorError}")
endif()

execute_process(COMMAND "${INK_PARSER}" "${MissingInput}" RESULT_VARIABLE MissingInputResult OUTPUT_VARIABLE MissingInputOutput ERROR_VARIABLE MissingInputError)
if(NOT MissingInputResult EQUAL 2 OR NOT "${MissingInputOutput}" STREQUAL "")
  message(FATAL_ERROR "missing-input process contract failed: result=${MissingInputResult}\nstdout=${MissingInputOutput}\nstderr=${MissingInputError}")
endif()
string(FIND "${MissingInputError}" "ink-parse: error: cannot open" MissingInputErrorOffset)
if(MissingInputErrorOffset EQUAL -1)
  message(FATAL_ERROR "missing-input error was not written to stderr: ${MissingInputError}")
endif()
