if(NOT EXISTS "${INK_TOKENIZER}")
  message(FATAL_ERROR "ink-tokenize executable does not exist: ${INK_TOKENIZER}")
endif()

file(MAKE_DIRECTORY "${INK_TEST_DIRECTORY}")
set(ValidInput "${INK_TEST_DIRECTORY}/valid.ink")
set(InvalidInput "${INK_TEST_DIRECTORY}/invalid.ink")
set(UnicodeInput "${INK_TEST_DIRECTORY}/源文件.ink")
set(DashInput "${INK_TEST_DIRECTORY}/-generated.ink")
set(MissingInput "${INK_TEST_DIRECTORY}/missing.ink")
set(GrammarInput "${INK_TEST_DIRECTORY}/grammar.ink")
set(CarriageReturnInput "${INK_TEST_DIRECTORY}/carriage-return.ink")
set(UnterminatedTripleInput "${INK_TEST_DIRECTORY}/unterminated-triple.ink")
file(WRITE "${ValidInput}" "class")
file(WRITE "${InvalidInput}" "\"")
file(WRITE "${UnicodeInput}" "class")
file(WRITE "${DashInput}" "class")
file(WRITE "${GrammarInput}" "let value: int32 = Point::[int32](1) >> 2; /* comment */\n")
file(WRITE "${CarriageReturnInput}" "value\r\"")
file(WRITE "${UnterminatedTripleInput}" [=[r"""unterminated]=])
file(REMOVE "${MissingInput}")

execute_process(COMMAND "${INK_TOKENIZER}" --help RESULT_VARIABLE HelpResult OUTPUT_VARIABLE HelpOutput ERROR_VARIABLE HelpError)
if(NOT HelpResult EQUAL 0 OR NOT "${HelpError}" STREQUAL "")
  message(FATAL_ERROR "help process contract failed: result=${HelpResult}\nstdout=${HelpOutput}\nstderr=${HelpError}")
endif()
string(FIND "${HelpOutput}" "ink-tokenize [OPTIONS] [INPUT]" HelpUsageOffset)
if(HelpUsageOffset EQUAL -1)
  message(FATAL_ERROR "help output does not contain the public invocation spelling: ${HelpOutput}")
endif()

execute_process(COMMAND "${INK_TOKENIZER}" INPUT_FILE "${ValidInput}" RESULT_VARIABLE ImplicitStdinResult OUTPUT_VARIABLE ImplicitStdinOutput ERROR_VARIABLE ImplicitStdinError)
if(NOT ImplicitStdinResult EQUAL 0 OR "${ImplicitStdinOutput}" STREQUAL "" OR NOT "${ImplicitStdinError}" STREQUAL "")
  message(FATAL_ERROR "implicit stdin process contract failed: result=${ImplicitStdinResult}\nstdout=${ImplicitStdinOutput}\nstderr=${ImplicitStdinError}")
endif()

execute_process(COMMAND "${INK_TOKENIZER}" - INPUT_FILE "${ValidInput}" RESULT_VARIABLE ExplicitStdinResult OUTPUT_VARIABLE ExplicitStdinOutput ERROR_VARIABLE ExplicitStdinError)
if(NOT ExplicitStdinResult EQUAL 0 OR "${ExplicitStdinOutput}" STREQUAL "" OR NOT "${ExplicitStdinError}" STREQUAL "")
  message(FATAL_ERROR "explicit stdin process contract failed: result=${ExplicitStdinResult}\nstdout=${ExplicitStdinOutput}\nstderr=${ExplicitStdinError}")
endif()

execute_process(COMMAND "${INK_TOKENIZER}" "${UnicodeInput}" RESULT_VARIABLE UnicodePathResult OUTPUT_VARIABLE UnicodePathOutput ERROR_VARIABLE UnicodePathError)
if(NOT UnicodePathResult EQUAL 0 OR "${UnicodePathOutput}" STREQUAL "" OR NOT "${UnicodePathError}" STREQUAL "")
  message(FATAL_ERROR "Unicode path process contract failed: result=${UnicodePathResult}\nstdout=${UnicodePathOutput}\nstderr=${UnicodePathError}")
endif()

execute_process(COMMAND "${INK_TOKENIZER}" -- -generated.ink WORKING_DIRECTORY "${INK_TEST_DIRECTORY}" RESULT_VARIABLE DashPathResult OUTPUT_VARIABLE DashPathOutput ERROR_VARIABLE DashPathError)
if(NOT DashPathResult EQUAL 0 OR "${DashPathOutput}" STREQUAL "" OR NOT "${DashPathError}" STREQUAL "")
  message(FATAL_ERROR "dash-leading path process contract failed: result=${DashPathResult}\nstdout=${DashPathOutput}\nstderr=${DashPathError}")
endif()

execute_process(COMMAND "${INK_TOKENIZER}" "${InvalidInput}" RESULT_VARIABLE SourceErrorResult OUTPUT_VARIABLE SourceErrorOutput ERROR_VARIABLE SourceErrorError)
execute_process(COMMAND "${INK_TOKENIZER}" "${GrammarInput}" RESULT_VARIABLE GrammarResult OUTPUT_VARIABLE GrammarOutput ERROR_VARIABLE GrammarError)
if(NOT GrammarResult EQUAL 0 OR NOT "${GrammarError}" STREQUAL "")
  message(FATAL_ERROR "new grammar tokenization failed: result=${GrammarResult}\nstdout=${GrammarOutput}\nstderr=${GrammarError}")
endif()
foreach(Spelling IN ITEMS "::" ">>" "int32")
  string(FIND "${GrammarOutput}" "\"${Spelling}\"" SpellingOffset)
  if(SpellingOffset EQUAL -1)
    message(FATAL_ERROR "token output lost an atomic grammar spelling '${Spelling}': ${GrammarOutput}")
  endif()
endforeach()
if(GrammarOutput MATCHES "SpacesAndTabs|LineBreak|BlockComment")
  message(FATAL_ERROR "default token output must discard trivia: ${GrammarOutput}")
endif()
execute_process(COMMAND "${INK_TOKENIZER}" --trivia "${GrammarInput}" RESULT_VARIABLE TriviaResult OUTPUT_VARIABLE TriviaOutput ERROR_VARIABLE TriviaError)
if(NOT TriviaResult EQUAL 0 OR NOT "${TriviaError}" STREQUAL "" OR NOT TriviaOutput MATCHES "BlockComment" OR NOT TriviaOutput MATCHES "LineBreak" OR NOT TriviaOutput MATCHES "SpacesAndTabs")
  message(FATAL_ERROR "explicit trivia output failed: result=${TriviaResult}\nstdout=${TriviaOutput}\nstderr=${TriviaError}")
endif()
execute_process(COMMAND "${INK_TOKENIZER}" "${CarriageReturnInput}" RESULT_VARIABLE CarriageReturnResult OUTPUT_VARIABLE CarriageReturnOutput ERROR_VARIABLE CarriageReturnError)
string(FIND "${CarriageReturnError}" "${CarriageReturnInput}:2:" CarriageReturnLocation)
if(NOT CarriageReturnResult EQUAL 1 OR CarriageReturnLocation EQUAL -1)
  message(FATAL_ERROR "CR source line diagnostics failed: result=${CarriageReturnResult}\nstderr=${CarriageReturnError}")
endif()
execute_process(COMMAND "${INK_TOKENIZER}" "${UnterminatedTripleInput}" RESULT_VARIABLE TripleResult OUTPUT_VARIABLE TripleOutput ERROR_VARIABLE TripleError)
if(NOT TripleResult EQUAL 1 OR NOT TripleOutput MATCHES "InvalidStringLiteral" OR NOT TripleError MATCHES "INK-T0025")
  message(FATAL_ERROR "unterminated raw triple string must fail without backtracking: result=${TripleResult}\nstdout=${TripleOutput}\nstderr=${TripleError}")
endif()
if(NOT SourceErrorResult EQUAL 1 OR "${SourceErrorOutput}" STREQUAL "")
  message(FATAL_ERROR "source-error process contract failed: result=${SourceErrorResult}\nstdout=${SourceErrorOutput}\nstderr=${SourceErrorError}")
endif()
string(FIND "${SourceErrorError}" "error[INK-" SourceDiagnosticOffset)
string(FIND "${SourceErrorError}" "${InvalidInput}:1:" SourceLocationOffset)
if(SourceDiagnosticOffset EQUAL -1 OR SourceLocationOffset EQUAL -1)
  message(FATAL_ERROR "source-error diagnostics did not include the source path and line on stderr: ${SourceErrorError}")
endif()

execute_process(COMMAND "${INK_TOKENIZER}" "${MissingInput}" RESULT_VARIABLE MissingInputResult OUTPUT_VARIABLE MissingInputOutput ERROR_VARIABLE MissingInputError)
if(NOT MissingInputResult EQUAL 2 OR NOT "${MissingInputOutput}" STREQUAL "")
  message(FATAL_ERROR "missing-input process contract failed: result=${MissingInputResult}\nstdout=${MissingInputOutput}\nstderr=${MissingInputError}")
endif()
string(FIND "${MissingInputError}" "ink-tokenize: error: cannot open" MissingInputErrorOffset)
if(MissingInputErrorOffset EQUAL -1)
  message(FATAL_ERROR "missing-input error was not written to stderr: ${MissingInputError}")
endif()

execute_process(COMMAND "${INK_TOKENIZER}" "${INK_TEST_DIRECTORY}" RESULT_VARIABLE DirectoryInputResult OUTPUT_VARIABLE DirectoryInputOutput ERROR_VARIABLE DirectoryInputError)
if(NOT DirectoryInputResult EQUAL 2 OR NOT "${DirectoryInputOutput}" STREQUAL "")
  message(FATAL_ERROR "directory-input process contract failed: result=${DirectoryInputResult}\nstdout=${DirectoryInputOutput}\nstderr=${DirectoryInputError}")
endif()
string(FIND "${DirectoryInputError}" "ink-tokenize: error: cannot " DirectoryInputErrorOffset)
if(DirectoryInputErrorOffset EQUAL -1)
  message(FATAL_ERROR "directory-input error was not written to stderr: ${DirectoryInputError}")
endif()

execute_process(COMMAND "${INK_TOKENIZER}" --unknown --help RESULT_VARIABLE UnknownOptionResult OUTPUT_VARIABLE UnknownOptionOutput ERROR_VARIABLE UnknownOptionError)
if(NOT UnknownOptionResult EQUAL 2 OR NOT "${UnknownOptionOutput}" STREQUAL "")
  message(FATAL_ERROR "unknown-option process contract failed: result=${UnknownOptionResult}\nstdout=${UnknownOptionOutput}\nstderr=${UnknownOptionError}")
endif()
string(FIND "${UnknownOptionError}" "ink-tokenize: error:" UnknownOptionErrorOffset)
if(UnknownOptionErrorOffset EQUAL -1)
  message(FATAL_ERROR "unknown-option error was not written to stderr: ${UnknownOptionError}")
endif()
