foreach(Required INK_COMPILER INK_CXX_COMPILER INK_RUNTIME INK_SOURCE INK_GOLDEN_STATUS INK_TEST_DIRECTORY)
  if(NOT DEFINED ${Required})
    message(FATAL_ERROR "Missing ${Required}")
  endif()
endforeach()

string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef RunId)
set(Directory "${INK_TEST_DIRECTORY}/${RunId}")
file(MAKE_DIRECTORY "${Directory}")
configure_file("${INK_SOURCE}" "${Directory}/program.ink" COPYONLY)
set(Source "${Directory}/program.ink")

execute_process(COMMAND "${INK_COMPILER}" --interpret -i "${Source}" RESULT_VARIABLE ExpectedStatus OUTPUT_VARIABLE ExpectedOutput ERROR_VARIABLE ExpectedError TIMEOUT 15)
if(NOT ExpectedStatus MATCHES "^[0-9]+$")
  message(FATAL_ERROR "Interpreter did not exit normally: ${ExpectedStatus}; ${ExpectedError}")
endif()
# Independent golden results prevent matching implementation mistakes in both execution paths.
set(ExpectedDiagnosticCode "${INK_GOLDEN_ERROR}")
string(REPLACE "|" "\n" GoldenOutput "${INK_GOLDEN_OUTPUT}")
string(REPLACE "\r\n" "\n" NormalizedOutput "${ExpectedOutput}")
if(NOT ExpectedStatus STREQUAL INK_GOLDEN_STATUS OR NOT NormalizedOutput STREQUAL GoldenOutput)
  message(FATAL_ERROR "Interpreter differs from the golden result: ${ExpectedStatus}; ${ExpectedOutput}; ${ExpectedError}")
endif()
if(ExpectedDiagnosticCode STREQUAL "")
  if(NOT ExpectedError STREQUAL "")
    message(FATAL_ERROR "Interpreter unexpectedly reported an error: ${ExpectedError}")
  endif()
elseif(NOT ExpectedError MATCHES "${ExpectedDiagnosticCode}")
  message(FATAL_ERROR "Interpreter did not report ${ExpectedDiagnosticCode}: ${ExpectedError}")
endif()

function(require_success Stage)
  execute_process(COMMAND ${ARGN} RESULT_VARIABLE Result OUTPUT_VARIABLE Output ERROR_VARIABLE Error TIMEOUT 30)
  if(NOT Result STREQUAL "0")
    message(FATAL_ERROR "${Stage} failed (${Result}): ${Output}${Error}; artifacts: ${Directory}")
  endif()
endfunction()

require_success(bytecode-compile "${INK_COMPILER}" --emit-bytecode "${Directory}/program.inkobj" --module-root "${Directory}" -i "${Source}")
require_success(bytecode-link "${INK_COMPILER}" --link-bytecode "${Directory}/program.inkobj" --entry "program#main" -o "${Directory}/program.inkbc")
execute_process(COMMAND "${INK_COMPILER}" --run-bytecode -i "${Directory}/program.inkbc" RESULT_VARIABLE BytecodeStatus OUTPUT_VARIABLE BytecodeOutput ERROR_VARIABLE BytecodeError TIMEOUT 15)
if(NOT BytecodeStatus STREQUAL ExpectedStatus OR NOT BytecodeOutput STREQUAL ExpectedOutput)
  message(FATAL_ERROR "Bytecode differs from interpretation: ${BytecodeStatus}; ${BytecodeOutput}; ${BytecodeError}")
endif()
if(NOT ExpectedDiagnosticCode STREQUAL "" AND NOT BytecodeError MATCHES "${ExpectedDiagnosticCode}")
  message(FATAL_ERROR "Bytecode reported a different runtime diagnostic: ${BytecodeError}")
endif()
if(ExpectedDiagnosticCode STREQUAL "" AND NOT BytecodeError STREQUAL "")
  message(FATAL_ERROR "Bytecode unexpectedly reported an error: ${BytecodeError}")
endif()

foreach(Level 0 2)
  set(Object "${Directory}/program-O${Level}.obj")
  set(Executable "${Directory}/program-O${Level}.exe")
  require_success("AOT O${Level} compile" "${INK_COMPILER}" --emit-object "${Object}" --opt-level "${Level}" -i "${Source}")
  if(INK_MSVC)
    if(INK_RUNTIME_KIND STREQUAL "MultiThreadedDebugDLL")
      set(RuntimeLibrary msvcrtd)
    elseif(INK_RUNTIME_KIND STREQUAL "MultiThreadedDLL")
      set(RuntimeLibrary msvcrt)
    elseif(INK_RUNTIME_KIND STREQUAL "MultiThreadedDebug")
      set(RuntimeLibrary libcmtd)
    else()
      set(RuntimeLibrary libcmt)
    endif()
    set(LibraryPaths "")
    foreach(Path IN LISTS INK_LINK_DIRECTORIES)
      list(APPEND LibraryPaths "/LIBPATH:${Path}")
    endforeach()
    separate_arguments(StandardLibraries NATIVE_COMMAND "${INK_STANDARD_LIBRARIES}")
    require_success("AOT O${Level} link" "${INK_LINKER}" /NOLOGO "/OUT:${Executable}" /SUBSYSTEM:CONSOLE "/DEFAULTLIB:${RuntimeLibrary}" "${Object}" "${INK_RUNTIME}" ${LibraryPaths} ${StandardLibraries})
  else()
    require_success("AOT O${Level} link" "${INK_CXX_COMPILER}" "${Object}" "${INK_RUNTIME}" -o "${Executable}")
  endif()
  execute_process(COMMAND "${Executable}" RESULT_VARIABLE ActualStatus OUTPUT_VARIABLE ActualOutput ERROR_VARIABLE ActualError TIMEOUT 15)
  file(WRITE "${Directory}/O${Level}.stderr" "${ActualError}")
  if(NOT ActualStatus STREQUAL ExpectedStatus OR NOT ActualOutput STREQUAL ExpectedOutput)
    message(FATAL_ERROR "AOT O${Level} differs: expected ${ExpectedStatus}, got ${ActualStatus}; ${ActualOutput}; ${ActualError}; artifacts: ${Directory}")
  endif()
  if(NOT ExpectedDiagnosticCode STREQUAL "")
    if(NOT ActualError MATCHES "${ExpectedDiagnosticCode}")
      message(FATAL_ERROR "AOT did not report the expected runtime diagnostic ${ExpectedDiagnosticCode}: ${ActualError}")
    endif()
  elseif(NOT ActualError STREQUAL "")
    message(FATAL_ERROR "Unexpected AOT stderr: ${ActualError}")
  endif()
endforeach()
