foreach(Required INK_COMPILER INK_CXX_COMPILER INK_RUNTIME INK_TEST_DIRECTORY INK_ROOT)
  if(NOT DEFINED ${Required})
    message(FATAL_ERROR "Missing ${Required}")
  endif()
endforeach()
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef RunId)
set(Directory "${INK_TEST_DIRECTORY}/${RunId}")
file(MAKE_DIRECTORY "${Directory}")
configure_file("${INK_ROOT}/src/testcase/backend/programs/reflection.ink" "${Directory}/program.ink" COPYONLY)
function(require_success Stage)
  execute_process(COMMAND ${ARGN} RESULT_VARIABLE Result OUTPUT_VARIABLE Output ERROR_VARIABLE Error TIMEOUT 40)
  if(NOT Result STREQUAL "0")
    message(FATAL_ERROR "${Stage} failed (${Result}): ${Output}${Error}; artifacts: ${Directory}")
  endif()
endfunction()
if(INK_MSVC)
  if(INK_RUNTIME_KIND STREQUAL "MultiThreadedDebugDLL")
    set(RuntimeFlag /MDd)
  elseif(INK_RUNTIME_KIND STREQUAL "MultiThreadedDLL")
    set(RuntimeFlag /MD)
  elseif(INK_RUNTIME_KIND STREQUAL "MultiThreadedDebug")
    set(RuntimeFlag /MTd)
  else()
    set(RuntimeFlag /MT)
  endif()
  require_success(host-compile "${INK_CXX_COMPILER}" /nologo /std:c++20 /EHs-c- /utf-8 "${RuntimeFlag}" "/I${INK_ROOT}/src/include" /c "${INK_ROOT}/src/testcase/backend/reflection_host.cpp" "/Fo${Directory}/host.obj")
else()
  require_success(host-compile "${INK_CXX_COMPILER}" -std=c++20 -fno-exceptions "-I${INK_ROOT}/src/include" -c "${INK_ROOT}/src/testcase/backend/reflection_host.cpp" -o "${Directory}/host.obj")
endif()
foreach(Level 0 2)
  set(Object "${Directory}/program-O${Level}.obj")
  set(Executable "${Directory}/program-O${Level}.exe")
  require_success(aot-compile "${INK_COMPILER}" --emit-object "${Object}" --opt-level "${Level}" --module-root "${Directory}" -i "${Directory}/program.ink")
  if(INK_MSVC)
    set(LibraryPaths "")
    foreach(Path IN LISTS INK_LINK_DIRECTORIES)
      list(APPEND LibraryPaths "/LIBPATH:${Path}")
    endforeach()
    separate_arguments(StandardLibraries NATIVE_COMMAND "${INK_STANDARD_LIBRARIES}")
    require_success(aot-link "${INK_LINKER}" /NOLOGO "/OUT:${Executable}" /SUBSYSTEM:CONSOLE "${Object}" "${Directory}/host.obj" "${INK_RUNTIME}" ${LibraryPaths} ${StandardLibraries})
  else()
    require_success(aot-link "${INK_CXX_COMPILER}" "${Object}" "${Directory}/host.obj" "${INK_RUNTIME}" -o "${Executable}")
  endif()
  require_success(reflection-execution "${Executable}")
endforeach()
