foreach(Required INK_COMPILER INK_TEST_DIRECTORY)
  if(NOT DEFINED ${Required})
    message(FATAL_ERROR "Missing ${Required}")
  endif()
endforeach()
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef RunId)
set(Directory "${INK_TEST_DIRECTORY}/${RunId}")
file(MAKE_DIRECTORY "${Directory}/a" "${Directory}/relocated/b")
file(WRITE "${Directory}/a/util.ink" "func answer(): i32 { return 42; }")
file(WRITE "${Directory}/relocated/b/util.ink" "// same declaration, changed body\nfunc answer(): i32 { return 43; }")
file(WRITE "${Directory}/a/main.ink" "import util as library; func unused(): i32 { return 1; } func main(): i32 { return library.answer(); }")
file(WRITE "${Directory}/relocated/b/main.ink" "import util as another; func main(): i32 { return another.answer(); } func unused(): i32 { return 2; }")
set(Package --package-authority org.example --package-name demo --package-revision 1.0.0 --package-variant feature=on --package-variant cfg=checked)
function(compile Root Level Output)
  execute_process(COMMAND "${INK_COMPILER}" --emit-llvm "${Output}" --opt-level "${Level}" --module-root "${Root}" ${Package} -i "${Root}/main.ink" RESULT_VARIABLE Result OUTPUT_VARIABLE Stdout ERROR_VARIABLE Stderr TIMEOUT 30)
  if(NOT Result STREQUAL "0")
    message(FATAL_ERROR "Compilation failed (${Result}): ${Stdout}${Stderr}; artifacts: ${Directory}")
  endif()
endfunction()
compile("${Directory}/a" 0 "${Directory}/a.ll")
compile("${Directory}/relocated/b" 2 "${Directory}/b.ll")
function(symbols Path Result)
  file(READ "${Path}" IR)
  string(REGEX MATCHALL "define [^\n]*@_INK2F[A-Za-z0-9_]+\\(" Definitions "${IR}")
  set(Names)
  foreach(Definition IN LISTS Definitions)
    string(REGEX MATCH "@(_INK2F[A-Za-z0-9_]+)\\(" Match "${Definition}")
    list(APPEND Names "${CMAKE_MATCH_1}")
  endforeach()
  list(SORT Names)
  list(LENGTH Names Count)
  if(NOT Count EQUAL 3)
    message(FATAL_ERROR "Expected three stable Ink function definitions in ${Path}, found ${Count}")
  endif()
  set(${Result} "${Names}" PARENT_SCOPE)
endfunction()
symbols("${Directory}/a.ll" A)
symbols("${Directory}/b.ll" B)
if(NOT A STREQUAL B)
  message(FATAL_ERROR "Source roots, aliases, order, optimization or body edits changed linkage identities")
endif()
execute_process(COMMAND "${INK_COMPILER}" --emit-object "${Directory}/program.obj" --module-root "${Directory}/a" ${Package} -i "${Directory}/a/main.ink" RESULT_VARIABLE Result ERROR_VARIABLE Error TIMEOUT 30)
if(NOT Result STREQUAL "0")
  message(FATAL_ERROR "Native object emission failed: ${Error}")
endif()
file(READ "${Directory}/program.obj" Object HEX)
if(NOT Object MATCHES "494e4b41424931")
  message(FATAL_ERROR "Native object is missing its INKABI1 contract metadata")
endif()
execute_process(COMMAND "${INK_COMPILER}" --emit-llvm "${Directory}/bad.ll" --package-name demo -i "${Directory}/a/main.ink" RESULT_VARIABLE Result ERROR_VARIABLE Error TIMEOUT 30)
if(Result STREQUAL "0" OR NOT Error MATCHES "package identity requires")
  message(FATAL_ERROR "Incomplete package identity was accepted: ${Error}")
endif()
