# The same source must survive serialization and native code generation at two optimization levels.
function(add_class_aot_test Name Source)
  cmake_parse_arguments(PARSE_ARGV 2 Test "" "STATUS;STDOUT;ERROR" "")
  if(NOT DEFINED Test_STATUS)
    set(Test_STATUS 42)
  endif()
  if(IS_ABSOLUTE "${Source}")
    set(SourcePath "${Source}")
  else()
    set(SourcePath "${CMAKE_CURRENT_SOURCE_DIR}/backend/programs/${Source}")
  endif()
  get_target_property(RuntimeKind ink_aot_runtime MSVC_RUNTIME_LIBRARY)
  if(NOT RuntimeKind)
    set(RuntimeKind "MultiThreaded$<$<CONFIG:Debug>:Debug>DLL")
  endif()
  add_test(NAME "AOTClassTest.${Name}" COMMAND "${CMAKE_COMMAND}" "-DINK_COMPILER=$<TARGET_FILE:inkc>" "-DINK_CXX_COMPILER=${CMAKE_CXX_COMPILER}" "-DINK_LINKER=${CMAKE_LINKER}" "-DINK_MSVC=${MSVC}" "-DINK_RUNTIME_KIND=${RuntimeKind}" "-DINK_RUNTIME=$<TARGET_FILE:ink_aot_runtime>" "-DINK_LINK_DIRECTORIES=${CMAKE_CXX_IMPLICIT_LINK_DIRECTORIES}" "-DINK_STANDARD_LIBRARIES=${CMAKE_CXX_STANDARD_LIBRARIES}" "-DINK_SOURCE=${SourcePath}" "-DINK_GOLDEN_STATUS=${Test_STATUS}" "-DINK_GOLDEN_OUTPUT=${Test_STDOUT}" "-DINK_GOLDEN_ERROR=${Test_ERROR}" "-DINK_TEST_DIRECTORY=${CMAKE_CURRENT_BINARY_DIR}/class-aot" -P "${CMAKE_CURRENT_SOURCE_DIR}/backend/aot_program_test.cmake")
  set_tests_properties("AOTClassTest.${Name}" PROPERTIES TIMEOUT 120 LABELS "class;aot;differential")
endfunction()

add_class_aot_test(ValueCopyAndMethod class_value.ink)
add_class_aot_test(Lifecycle class_lifecycle.ink STDOUT "init|init|pair|drop2|drop1|init|init|drop2|drop1|init|drop2|init|init|drop2|drop1|")
add_class_aot_test(LifecycleTransfer class_lifecycle_transfer.ink)
add_class_aot_test(NestedArraysAndAliases class_nested.ink)
add_class_aot_test(WideFieldsAndEmptyObjects class_layout.ink)
add_class_aot_test(EscapedAddressCanBeDiscarded class_expired.ink)
add_class_aot_test(ArrayBounds class_bounds.ink STATUS 1 ERROR "INK-E0025")
add_class_aot_test(ArrayBoundsPreservesOutput class_bounds_output.ink STATUS 1 STDOUT "before bounds failure|" ERROR "INK-E0025")
add_class_aot_test(SignedArrayIndex class_negative_index.ink STATUS 1 ERROR "INK-E0025")
add_class_aot_test(DefaultsAndEvaluationOrder class_effects.ink STDOUT "default|default|receiver|default|argument|method|")
add_class_aot_test(OperatorCopiesLeftOperand class_operator.ink STDOUT "left|right|add|add|equal|negative|")
add_class_aot_test(NativeClassStorage class_native_storage.ink)
if(CMAKE_SIZEOF_VOID_P EQUAL 8)
  add_class_aot_test(NativeClassMemcpy class_memcpy.ink STATUS 43)
  add_class_aot_test(NativeBooleanWriteBack native_boolean.ink)
endif()
add_class_aot_test(NativePointerOutParameter raw_pointer_out_parameter.ink)
add_class_aot_test(Loops loops.ink)
add_class_aot_test(GenericTypes "${CMAKE_CURRENT_SOURCE_DIR}/execution/programs/generic_types.ink" STATUS 0 STDOUT "Generic.types|PASS|Generic.arrays_and_pointers|PASS|Generic.class_copy|PASS|Generic.function_value|PASS|")
add_class_aot_test(GenericValues "${CMAKE_CURRENT_SOURCE_DIR}/execution/programs/generic_values.ink" STATUS 0 STDOUT "Generic.defaults|PASS|Generic.frozen_values|PASS|Generic.argument_order|PASS|Generic.comptime|PASS|")
add_class_aot_test(GenericRecursion "${CMAKE_CURRENT_SOURCE_DIR}/execution/programs/generic_recursion.ink" STATUS 0 STDOUT "Generic.recursion|PASS|Generic.overloads|PASS|Generic.nested|PASS|")
set_tests_properties(AOTClassTest.GenericTypes AOTClassTest.GenericValues AOTClassTest.GenericRecursion PROPERTIES LABELS "generic;aot;differential")
add_class_aot_test(LoopLifecycle loop_lifecycle.ink STDOUT "body|inner|body|inner|body|header|body|header|body|inner|body|body|body|inner|inner|")
set_tests_properties(AOTClassTest.Loops AOTClassTest.LoopLifecycle PROPERTIES LABELS "loops;control_flow;aot;differential")
add_class_aot_test(SharedMethodsDefaults "${CMAKE_CURRENT_SOURCE_DIR}/execution/class_programs/methods_defaults.ink" STATUS 0 STDOUT "Class.defaults|default|PASS|Class.pointer_method|default|PASS|Class.temporary_method|default|PASS|")
add_class_aot_test(SharedValuesAndPointers "${CMAKE_CURRENT_SOURCE_DIR}/execution/class_programs/values_dunder.ink" STATUS 0 STDOUT "Class.dunder_snapshot|PASS|Class.nested_alias|PASS|Class.pointer_field_copy|PASS|")
add_class_aot_test(SharedComptime "${CMAKE_CURRENT_SOURCE_DIR}/execution/class_programs/comptime.ink" STATUS 0 STDOUT "Class.comptime_return|PASS|Class.comptime_nested|PASS|")
add_class_aot_test(SharedMethodEffects "${CMAKE_CURRENT_SOURCE_DIR}/execution/class_programs/effects.ink" STATUS 0 STDOUT "Class.method_order|receiver|argument|method|PASS|")

get_target_property(ReflectionRuntimeKind ink_aot_runtime MSVC_RUNTIME_LIBRARY)
if(NOT ReflectionRuntimeKind)
  set(ReflectionRuntimeKind "MultiThreaded$<$<CONFIG:Debug>:Debug>DLL")
endif()
add_test(NAME AOTReflectionTest COMMAND "${CMAKE_COMMAND}" "-DINK_COMPILER=$<TARGET_FILE:inkc>" "-DINK_CXX_COMPILER=${CMAKE_CXX_COMPILER}" "-DINK_LINKER=${CMAKE_LINKER}" "-DINK_MSVC=${MSVC}" "-DINK_RUNTIME_KIND=$<GENEX_EVAL:${ReflectionRuntimeKind}>" "-DINK_RUNTIME=$<TARGET_FILE:ink_aot_runtime>" "-DINK_LINK_DIRECTORIES=${CMAKE_CXX_IMPLICIT_LINK_DIRECTORIES}" "-DINK_STANDARD_LIBRARIES=${CMAKE_CXX_STANDARD_LIBRARIES}" "-DINK_ROOT=${PROJECT_SOURCE_DIR}" "-DINK_TEST_DIRECTORY=${CMAKE_CURRENT_BINARY_DIR}/reflection-aot" -P "${CMAKE_CURRENT_SOURCE_DIR}/backend/reflection_test.cmake")
set_tests_properties(AOTReflectionTest PROPERTIES TIMEOUT 120 LABELS "reflection;aot")
