import argparse
import pathlib
import sys

from schema import OPCODES, PLAN_OPCODES, VARIADIC


ROOT = pathlib.Path(__file__).resolve().parents[2]
OPCODE_OUTPUT = ROOT / "src" / "include" / "ink" / "ir" / "generated" / "opcode.def"
PLAN_OPCODE_OUTPUT = ROOT / "src" / "include" / "ink" / "ir" / "generated" / "plan_opcode.def"
PAYLOADS = {"None", "Constant", "Compare", "Type", "DirectCall", "Trap"}
EFFECTS = {"Pure", "ReadMemory", "WriteMemory", "Allocate", "Call", "Control", "MayTrap", "TargetDependent", "PdbBoundary", "Runtime"}
STAGES = {"Staged", "Closed"}


def validate() -> None:
    names: set[str] = set()
    mnemonics: set[str] = set()
    for opcode in OPCODES:
        if opcode.name in names:
            raise ValueError(f"duplicate opcode name: {opcode.name}")
        if opcode.mnemonic in mnemonics:
            raise ValueError(f"duplicate opcode mnemonic: {opcode.mnemonic}")
        if opcode.payload not in PAYLOADS:
            raise ValueError(f"unknown payload kind for {opcode.name}: {opcode.payload}")
        if not set(opcode.effects).issubset(EFFECTS):
            raise ValueError(f"unknown effect for {opcode.name}")
        if not opcode.effects:
            raise ValueError(f"opcode has no declared effect: {opcode.name}")
        if not set(opcode.stages).issubset(STAGES) or not opcode.stages:
            raise ValueError(f"invalid stage set for {opcode.name}")
        if not 0 <= opcode.min_operands <= opcode.max_operands <= VARIADIC:
            raise ValueError(f"invalid operand arity for {opcode.name}")
        if not 0 <= opcode.min_results <= opcode.max_results <= VARIADIC:
            raise ValueError(f"invalid result arity for {opcode.name}")
        if opcode.successors and not opcode.terminator:
            raise ValueError(f"non-terminator has successors: {opcode.name}")
        names.add(opcode.name)
        mnemonics.add(opcode.mnemonic)
    for opcode in PLAN_OPCODES:
        if opcode.name in names:
            raise ValueError(f"duplicate opcode name: {opcode.name}")
        if opcode.mnemonic in mnemonics:
            raise ValueError(f"duplicate opcode mnemonic: {opcode.mnemonic}")
        if not 0 <= opcode.min_inputs <= opcode.max_inputs <= VARIADIC:
            raise ValueError(f"invalid plan input arity for {opcode.name}")
        if not 0 <= opcode.result_count <= VARIADIC:
            raise ValueError(f"invalid plan result arity for {opcode.name}")
        if not set(opcode.stages).issubset(STAGES) or not opcode.stages:
            raise ValueError(f"invalid plan stage set for {opcode.name}")
        names.add(opcode.name)
        mnemonics.add(opcode.mnemonic)


def flags(values: tuple[str, ...], prefix: str) -> str:
    return " | ".join(f"{prefix}::{value}" for value in values)


def render_opcodes() -> str:
    validate()
    lines = [
        "// Generated by tools/ir_schema/generate_ir_schema.py. Do not edit.",
        "// clang-format off",
    ]
    for opcode in OPCODES:
        lines.append(f'INK_IR_OPCODE({opcode.name}, "{opcode.mnemonic}", {opcode.payload}, {opcode.min_operands}, {opcode.max_operands}, {opcode.min_results}, {opcode.max_results}, {opcode.successors}, {str(opcode.terminator).lower()}, {flags(opcode.effects, "IrEffect")}, {flags(opcode.stages, "IrStage")})')
    lines.extend(("// clang-format on", ""))
    return "\n".join(lines)


def render_plan_opcodes() -> str:
    validate()
    lines = [
        "// Generated by tools/ir_schema/generate_ir_schema.py. Do not edit.",
        "// clang-format off",
    ]
    for opcode in PLAN_OPCODES:
        lines.append(f'INK_IR_PLAN_OPCODE({opcode.name}, "{opcode.mnemonic}", {opcode.min_inputs}, {opcode.max_inputs}, {opcode.result_count}, {flags(opcode.stages, "IrStage")})')
    lines.extend(("// clang-format on", ""))
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate the compact first-slice InkIR opcode registry.")
    parser.add_argument("--check", action="store_true", help="Fail if the checked-in generated registry is stale.")
    arguments = parser.parse_args()
    generated = {
        OPCODE_OUTPUT: render_opcodes(),
        PLAN_OPCODE_OUTPUT: render_plan_opcodes(),
    }
    if arguments.check:
        for output, content in generated.items():
            if not output.exists() or output.read_text(encoding="utf-8") != content:
                print(f"stale generated InkIR registry: {output}", file=sys.stderr)
                return 1
        return 0
    for output, content in generated.items():
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(content, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
