function(require_success Stage)
  execute_process(COMMAND ${ARGN} RESULT_VARIABLE Result OUTPUT_VARIABLE Output ERROR_VARIABLE Error TIMEOUT 40)
  if(NOT Result STREQUAL "0")
    message(FATAL_ERROR "${Stage} failed (${Result}): ${Output}${Error}")
  endif()
endfunction()

file(MAKE_DIRECTORY "${DIRECTORY}")
set(BASE 1)
set(STEP 10)
set(EXTRA 0)
set(HELPER "")
set(HELPER_CALL 0)
configure_file("${SOURCE}" "${DIRECTORY}/program.ink" @ONLY)
require_success(native "${COMPILER}" -i "${DIRECTORY}/program.ink" --library --hot-reload --hot-manifest "${DIRECTORY}/program.base" --emit-object "${DIRECTORY}/program.obj" --opt-level "${LEVEL}")
set(BASE 100)
set(EXTRA 1)
set(HELPER "private func patchHelper(Value: i64): i32 { return 0; }")
set(HELPER_CALL "patchHelper(0)")
configure_file("${SOURCE}" "${DIRECTORY}/program.ink" @ONLY)
require_success(first-patch "${COMPILER}" -i "${DIRECTORY}/program.ink" --emit-patch "${DIRECTORY}/first.patch" --patch-base "${DIRECTORY}/program.base" --patch-function "program#f" --patch-function "program#copy" --patch-function "program#array" --patch-function "program#hybridBusy" --patch-function "program#patchHelper")
set(STEP 20)
configure_file("${SOURCE}" "${DIRECTORY}/program.ink" @ONLY)
require_success(bounce-patch "${COMPILER}" -i "${DIRECTORY}/program.ink" --emit-patch "${DIRECTORY}/bounce.patch" --patch-base "${DIRECTORY}/program.base" --patch-function "program#bounce" --patch-function "program#patchHelper")
set(BASE 200)
configure_file("${SOURCE}" "${DIRECTORY}/program.ink" @ONLY)
require_success(second-patch "${COMPILER}" -i "${DIRECTORY}/program.ink" --emit-patch "${DIRECTORY}/second.patch" --patch-base "${DIRECTORY}/program.base" --patch-function "program#f" --patch-function "program#patchHelper")

# A changed object layout must be rejected while compiling the patch.
file(READ "${DIRECTORY}/program.ink" Changed)
string(REPLACE "field Weight: i32;" "field Weight: i32; field Added: i32 = 0;" Changed "${Changed}")
file(WRITE "${DIRECTORY}/program.ink" "${Changed}")
execute_process(COMMAND "${COMPILER}" -i "${DIRECTORY}/program.ink" --emit-patch "${DIRECTORY}/invalid.patch" --patch-base "${DIRECTORY}/program.base" --patch-function "program#f" RESULT_VARIABLE Result OUTPUT_VARIABLE Output ERROR_VARIABLE Error)
if(Result STREQUAL "0" OR NOT Error MATCHES "layout or interface")
  message(FATAL_ERROR "Incompatible class layout was not rejected: ${Result}: ${Output}${Error}")
endif()
