foreach(Level 0 2)
  set(Directory "${CMAKE_CURRENT_BINARY_DIR}/hybrid-O${Level}")
  set(FixtureSource "${CMAKE_CURRENT_SOURCE_DIR}/backend/hybrid/program.ink.in")
  set(GenerateScript "${CMAKE_CURRENT_SOURCE_DIR}/backend/hybrid/generate.cmake")
  add_custom_command(OUTPUT "${Directory}/program.obj" "${Directory}/program.base" "${Directory}/first.patch" "${Directory}/bounce.patch" "${Directory}/second.patch" COMMAND "${CMAKE_COMMAND}" "-DCOMPILER=$<TARGET_FILE:inkc>" "-DSOURCE=${FixtureSource}" "-DDIRECTORY=${Directory}" "-DLEVEL=${Level}" -P "${GenerateScript}" DEPENDS inkc "${FixtureSource}" "${GenerateScript}" VERBATIM)
  set_source_files_properties("${Directory}/program.obj" PROPERTIES EXTERNAL_OBJECT TRUE GENERATED TRUE)
  add_executable(ink_hybrid_test_O${Level} "${CMAKE_CURRENT_SOURCE_DIR}/backend/hybrid/host.cpp" "${Directory}/program.obj")
  target_link_libraries(ink_hybrid_test_O${Level} PRIVATE ink::hybrid_runtime spdlog::spdlog)
  ink_disable_exceptions(ink_hybrid_test_O${Level})
  add_dependencies(ink_tests ink_hybrid_test_O${Level})
  add_test(NAME HybridExecutionTest.O${Level} COMMAND ink_hybrid_test_O${Level} "${Directory}")
  set_tests_properties(HybridExecutionTest.O${Level} PROPERTIES TIMEOUT 60 LABELS "hybrid;aot;execution")
endforeach()
