"""Generate the complete Unicode 15.1 alias table used by named escapes.

Usage:
  python cmake/generate_unicode_aliases.py NameAliases.txt src/lib/tokenizer/unicode_name_aliases.inc

Input: https://www.unicode.org/Public/15.1.0/ucd/NameAliases.txt
XID and normalization data remain supplied by Clang and utf8proc.
"""

import argparse
import hashlib
from pathlib import Path


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    content = args.source.read_bytes()
    if not content.startswith(b"# NameAliases-15.1.0.txt"):
        parser.error("expected the official Unicode 15.1.0 NameAliases.txt")

    entries = []
    for line in content.decode("utf-8").splitlines():
        line = line.partition("#")[0].strip()
        if line:
            codepoint, name, _ = line.split(";")
            entries.append((name, int(codepoint, 16)))
    entries.sort()
    if len({name for name, _ in entries}) != len(entries):
        parser.error("duplicate Unicode aliases")

    digest = hashlib.sha256(content).hexdigest()
    lines = [
        "// Generated by cmake/generate_unicode_aliases.py; do not edit.",
        "// Source: https://www.unicode.org/Public/15.1.0/ucd/NameAliases.txt",
        f"// SHA-256: {digest}",
        "// Unicode data copyright 2023 Unicode, Inc.",
        "// Terms of use: https://www.unicode.org/terms_of_use.html",
        "// Permission notice: UNICODE-LICENSE.txt in this directory.",
        "// Includes correction, control, alternate, figment and abbreviation aliases.",
    ]
    lines.extend(f'{{"{name}", 0x{codepoint:04X}}},' for name, codepoint in entries)
    args.output.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
