option(INK_ENABLE_PARSER_COVERAGE "Instrument the parser and add its coverage report and gate" OFF)
option(INK_PARSER_COVERAGE_INCLUDE_INTEGRATION "Include the CodeContests parser corpus in coverage runs" OFF)
set(INK_PARSER_COVERAGE_MIN_LINES "85" CACHE STRING "Minimum parser line coverage percentage")
set(INK_PARSER_COVERAGE_MIN_FUNCTIONS "85" CACHE STRING "Minimum parser function coverage percentage")
set(INK_PARSER_COVERAGE_MIN_BRANCHES "55" CACHE STRING "Minimum parser branch coverage percentage")

function(ink_add_parser_coverage)
  if(NOT INK_ENABLE_PARSER_COVERAGE)
    return()
  endif()

  if(NOT BUILD_TESTING)
    message(FATAL_ERROR "INK_ENABLE_PARSER_COVERAGE requires BUILD_TESTING=ON")
  endif()
  if(NOT TARGET ink_parser OR NOT TARGET ink_tests)
    message(FATAL_ERROR "Parser coverage must be configured after ink_parser and ink_tests")
  endif()

  find_package(Python3 3.8 REQUIRED COMPONENTS Interpreter)
  get_filename_component(InkCompilerDirectory "${CMAKE_CXX_COMPILER}" DIRECTORY)

  if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
    find_program(INK_GCOV_EXECUTABLE NAMES gcov HINTS "${InkCompilerDirectory}" NO_DEFAULT_PATH)
    if(NOT INK_GCOV_EXECUTABLE)
      find_program(INK_GCOV_EXECUTABLE NAMES gcov REQUIRED)
    endif()
    set(InkCoverageBackend gcc)
    set(InkCoverageToolArguments --gcov "${INK_GCOV_EXECUTABLE}")
    target_compile_options(ink_parser PRIVATE -O0 -g --coverage)
    target_compile_options(ink_tests PRIVATE -O0 -g --coverage)
    target_link_options(ink_parser INTERFACE --coverage)
  elseif(CMAKE_CXX_COMPILER_ID MATCHES "^(Apple)?Clang$" AND NOT CMAKE_CXX_SIMULATE_ID STREQUAL "MSVC")
    string(REGEX MATCH "^[0-9]+" InkCompilerMajor "${CMAKE_CXX_COMPILER_VERSION}")
    find_program(INK_LLVM_PROFDATA_EXECUTABLE NAMES "llvm-profdata-${InkCompilerMajor}" llvm-profdata HINTS "${InkCompilerDirectory}")
    find_program(INK_LLVM_COV_EXECUTABLE NAMES "llvm-cov-${InkCompilerMajor}" llvm-cov HINTS "${InkCompilerDirectory}")
    if(NOT INK_LLVM_PROFDATA_EXECUTABLE OR NOT INK_LLVM_COV_EXECUTABLE)
      message(FATAL_ERROR "Clang parser coverage requires matching llvm-profdata and llvm-cov executables")
    endif()
    set(InkCoverageBackend clang)
    set(InkCoverageToolArguments --llvm-profdata "${INK_LLVM_PROFDATA_EXECUTABLE}" --llvm-cov "${INK_LLVM_COV_EXECUTABLE}")
    target_compile_options(ink_parser PRIVATE -O0 -g -fprofile-instr-generate -fcoverage-mapping)
    target_compile_options(ink_tests PRIVATE -O0 -g -fprofile-instr-generate -fcoverage-mapping)
    target_link_options(ink_parser INTERFACE -fprofile-instr-generate -fcoverage-mapping)
  else()
    message(FATAL_ERROR "Parser coverage supports GCC and GNU-style Clang toolchains; current compiler is ${CMAKE_CXX_COMPILER_ID}")
  endif()

  set(InkParserTestFilter "Parser*")
  if(INK_PARSER_COVERAGE_INCLUDE_INTEGRATION)
    set(InkParserTestFilter "Parser*:*/ParserIntegrationTest.*")
  endif()

  set(InkParserCoverageReportDirectory "${CMAKE_BINARY_DIR}/parser-coverage/$<CONFIG>")
  set(InkParserCoverageCommand "${Python3_EXECUTABLE}" "${PROJECT_SOURCE_DIR}/cmake/parser_coverage.py" --backend "${InkCoverageBackend}" --test-executable "$<TARGET_FILE:ink_tests>" --test-filter "${InkParserTestFilter}" --source-root "${PROJECT_SOURCE_DIR}" --build-root "${CMAKE_BINARY_DIR}" --report-directory "${InkParserCoverageReportDirectory}" --minimum-lines "${INK_PARSER_COVERAGE_MIN_LINES}" --minimum-functions "${INK_PARSER_COVERAGE_MIN_FUNCTIONS}" --minimum-branches "${INK_PARSER_COVERAGE_MIN_BRANCHES}" ${InkCoverageToolArguments})

  add_custom_target(parser_coverage COMMAND ${InkParserCoverageCommand} DEPENDS ink_tests COMMENT "Running focused parser tests and enforcing parser coverage thresholds" USES_TERMINAL VERBATIM)
  add_test(NAME ParserCoverage COMMAND ${InkParserCoverageCommand})
  set_tests_properties(ParserCoverage PROPERTIES LABELS "coverage;parser" RUN_SERIAL TRUE)
endfunction()
