execute_process(COMMAND "${INK_LIBFFI_C_COMPILER}" /nologo /EP /DFFI_STATIC_BUILD /DX86_WIN64 "/I${INK_LIBFFI_GENERATED_INCLUDE}" "/I${INK_LIBFFI_SOURCE_INCLUDE}" "/I${INK_LIBFFI_TARGET_INCLUDE}" "${INK_LIBFFI_SOURCE}" OUTPUT_FILE "${INK_LIBFFI_OUTPUT}" RESULT_VARIABLE INK_LIBFFI_PREPROCESS_RESULT)

if(NOT INK_LIBFFI_PREPROCESS_RESULT EQUAL 0)
  message(FATAL_ERROR "Failed to preprocess the libffi Windows x64 assembly source")
endif()
