cmake_minimum_required(VERSION 3.20)

if(NOT DEFINED INK_COMPILER OR NOT DEFINED INK_CASE_DIRECTORY OR NOT DEFINED INK_TEST_DIRECTORY)
  message(FATAL_ERROR "Compiler, case directory and test output directory are required")
endif()
file(GLOB_RECURSE CaseSources RELATIVE "${INK_CASE_DIRECTORY}" "${INK_CASE_DIRECTORY}/*.ink")
list(SORT CaseSources)
list(LENGTH CaseSources SourceCount)
if(SourceCount LESS 2)
  message(FATAL_ERROR "A multi-file case requires at least two Ink source files: ${INK_CASE_DIRECTORY}")
endif()
string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef RunId)
set(RunDirectory "${INK_TEST_DIRECTORY}/${RunId}")
set(SourceDirectory "${RunDirectory}/sources")
file(MAKE_DIRECTORY "${SourceDirectory}")
foreach(Source IN LISTS CaseSources)
  configure_file("${INK_CASE_DIRECTORY}/${Source}" "${SourceDirectory}/${Source}" COPYONLY)
endforeach()
set(CaseFinished FALSE)

# Visibility, names and dependencies come exclusively from source; each command uses a fresh process.
function(run_multifile_command Name ExpectedStatus ExpectedError)
  execute_process(COMMAND "${INK_COMPILER}" ${ARGN} WORKING_DIRECTORY "${RunDirectory}" RESULT_VARIABLE Status OUTPUT_VARIABLE Output ERROR_VARIABLE Error TIMEOUT 20)
  file(WRITE "${RunDirectory}/${Name}.stdout" "${Output}")
  file(WRITE "${RunDirectory}/${Name}.stderr" "${Error}")
  if(NOT "${Status}" STREQUAL "${ExpectedStatus}")
    message(FATAL_ERROR "${Name}: expected exit ${ExpectedStatus}, got '${Status}'; stdout: ${Output}; stderr: ${Error}; artifacts: ${RunDirectory}")
  endif()
  if(NOT Output STREQUAL "")
    message(FATAL_ERROR "${Name}: unexpected stdout '${Output}'; artifacts: ${RunDirectory}")
  endif()
  if(ExpectedError STREQUAL "")
    if(NOT Error STREQUAL "")
      message(FATAL_ERROR "${Name}: unexpected stderr '${Error}'; artifacts: ${RunDirectory}")
    endif()
  elseif(NOT Error MATCHES "${ExpectedError}")
    message(FATAL_ERROR "${Name}: expected diagnostic '${ExpectedError}', got '${Error}'; artifacts: ${RunDirectory}")
  endif()
endfunction()

# Every .ink file is compiled independently, deriving module identity from the common source root.
function(compile_multifile_sources FailedModule ExpectedError)
  if(CaseFinished)
    message(FATAL_ERROR "Each case must declare exactly one outcome: ${INK_CASE_DIRECTORY}")
  endif()
  set(ModuleNames)
  foreach(Source IN LISTS CaseSources)
    string(REGEX REPLACE "[.]ink$" "" Module "${Source}")
    string(REPLACE "/" "." Module "${Module}")
    set(Object "${RunDirectory}/${Module}.inkobj")
    if(Module STREQUAL FailedModule)
      run_multifile_command("compile_${Module}" 1 "${ExpectedError}" --emit-bytecode "${Object}" --module-root "${SourceDirectory}" -i "${SourceDirectory}/${Source}")
      if(EXISTS "${Object}")
        message(FATAL_ERROR "Rejected source published '${Object}'")
      endif()
    else()
      run_multifile_command("compile_${Module}" 0 "" --emit-bytecode "${Object}" --module-root "${SourceDirectory}" -i "${SourceDirectory}/${Source}")
      if(NOT EXISTS "${Object}")
        message(FATAL_ERROR "Compilation did not produce '${Object}'")
      endif()
    endif()
    list(APPEND ModuleNames "${Module}")
  endforeach()
  if(NOT FailedModule STREQUAL "" AND NOT FailedModule IN_LIST ModuleNames)
    message(FATAL_ERROR "Expected failing module '${FailedModule}' has no source in ${INK_CASE_DIRECTORY}")
  endif()
  set(ModuleNames "${ModuleNames}" PARENT_SCOPE)
endfunction()

function(link_multifile_program Name Entry)
  set(Arguments --entry "${Entry}" -o "${RunDirectory}/${Name}.inkbc")
  foreach(Module IN LISTS ModuleNames)
    list(APPEND Arguments --link-bytecode "${RunDirectory}/${Module}.inkobj")
  endforeach()
  run_multifile_command("link_${Name}" 0 "" ${Arguments})
  if(NOT EXISTS "${RunDirectory}/${Name}.inkbc")
    message(FATAL_ERROR "Linking did not produce '${Name}.inkbc'; artifacts: ${RunDirectory}")
  endif()
endfunction()

# The same source imports work during interpretation and after linking in either object order.
function(expect_bytecode_result Entry ExpectedStatus)
  compile_multifile_sources("" "")
  string(REGEX REPLACE "#.*$" "" EntryModule "${Entry}")
  string(REGEX REPLACE "^[^#]*#" "" EntryFunction "${Entry}")
  if(NOT EntryModule IN_LIST ModuleNames OR EntryFunction STREQUAL Entry)
    message(FATAL_ERROR "Entry must use an existing module#function: ${Entry}")
  endif()
  string(REPLACE "." "/" EntrySource "${EntryModule}")
  run_multifile_command(interpret "${ExpectedStatus}" "" --interpret --module-root "${SourceDirectory}" --entry "${EntryFunction}" -i "${SourceDirectory}/${EntrySource}.ink")
  link_multifile_program(program "${Entry}")
  list(REVERSE ModuleNames)
  link_multifile_program(reversed "${Entry}")
  foreach(Source IN LISTS CaseSources)
    file(RENAME "${SourceDirectory}/${Source}" "${SourceDirectory}/${Source}.unavailable")
  endforeach()
  foreach(Module IN LISTS ModuleNames)
    file(RENAME "${RunDirectory}/${Module}.inkobj" "${RunDirectory}/${Module}.object-unavailable")
  endforeach()
  run_multifile_command(run_program "${ExpectedStatus}" "" --run-bytecode -i "${RunDirectory}/program.inkbc")
  run_multifile_command(run_reversed "${ExpectedStatus}" "" --run-bytecode -i "${RunDirectory}/reversed.inkbc")
  set(CaseFinished TRUE PARENT_SCOPE)
endfunction()

# Invalid imports, visibility and prohibited declarations fail in source analysis without publishing an object.
function(expect_bytecode_source_error Module ExpectedError)
  if(Module STREQUAL "" OR ExpectedError STREQUAL "")
    message(FATAL_ERROR "A source rejection requires a module and diagnostic: ${INK_CASE_DIRECTORY}")
  endif()
  compile_multifile_sources("${Module}" "${ExpectedError}")
  set(CaseFinished TRUE PARENT_SCOPE)
endfunction()

include("${INK_CASE_DIRECTORY}/case.cmake")
if(NOT CaseFinished)
  message(FATAL_ERROR "Case must assert a source error or execution result: ${INK_CASE_DIRECTORY}")
endif()
