if(NOT DEFINED INK_COMPILER OR NOT DEFINED INK_SOURCE OR NOT DEFINED INK_TEST_DIRECTORY OR NOT DEFINED INK_EXPECTED_STATUS OR NOT DEFINED INK_EXPECTED_STDOUT OR NOT DEFINED INK_EXPECTED_ERROR)
  message(FATAL_ERROR "Compiler, source, test directory and expected process results are required")
endif()

# Give every source/bytecode invocation private output files and a fresh stdin stream.
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef RunId)
set(RunDirectory "${INK_TEST_DIRECTORY}/source-program-${RunId}")
file(MAKE_DIRECTORY "${RunDirectory}")
set(InputOptions "")
if(DEFINED INK_STDIN_FILE AND NOT INK_STDIN_FILE STREQUAL "")
  set(InputOptions INPUT_FILE "${INK_STDIN_FILE}")
endif()

function(check_program_process Mode ExpectedStatus ExpectedOutput ExpectedError ExpectedHex)
  set(OutputFile "${RunDirectory}/${Mode}.stdout")
  execute_process(COMMAND "${INK_COMPILER}" ${ARGN} ${InputOptions} RESULT_VARIABLE Status OUTPUT_FILE "${OutputFile}" ERROR_VARIABLE Error TIMEOUT 15)
  file(READ "${OutputFile}" Output)
  file(WRITE "${RunDirectory}/${Mode}.stderr" "${Error}")
  if(NOT "${Status}" STREQUAL "${ExpectedStatus}")
    message(FATAL_ERROR "${INK_SOURCE}:${Mode}: expected exit ${ExpectedStatus}, got '${Status}'; stdout: ${Output}; stderr: ${Error}; artifacts: ${RunDirectory}")
  endif()

  # The manifest uses | for newline; normalize the CRT's CRLF but assert all other bytes exactly.
  string(REPLACE "|" "\n" ExpectedOutput "${ExpectedOutput}")
  string(REPLACE "\r\n" "\n" NormalizedOutput "${Output}")
  if(NOT NormalizedOutput STREQUAL ExpectedOutput)
    message(FATAL_ERROR "${INK_SOURCE}:${Mode}: stdout differs; expected '${ExpectedOutput}', got '${NormalizedOutput}'; artifacts: ${RunDirectory}")
  endif()
  if(NOT ExpectedHex STREQUAL "")
    file(READ "${OutputFile}" OutputHex HEX)
    string(TOLOWER "${ExpectedHex}" ExpectedOutputHex)
    if(NOT OutputHex STREQUAL ExpectedOutputHex)
      message(FATAL_ERROR "${INK_SOURCE}:${Mode}: stdout bytes differ; expected '${ExpectedOutputHex}', got '${OutputHex}'; file: ${OutputFile}")
    endif()
  endif()
  if(ExpectedError STREQUAL "")
    if(NOT Error STREQUAL "")
      message(FATAL_ERROR "${INK_SOURCE}:${Mode}: unexpected stderr: ${Error}")
    endif()
  elseif(NOT Error MATCHES "${ExpectedError}")
    message(FATAL_ERROR "${INK_SOURCE}:${Mode}: expected diagnostic '${ExpectedError}', got: ${Error}")
  endif()
endfunction()

check_program_process(source "${INK_EXPECTED_STATUS}" "${INK_EXPECTED_STDOUT}" "${INK_EXPECTED_ERROR}" "${INK_EXPECTED_STDOUT_HEX}" --interpret -i "${INK_SOURCE}")
if(INK_TEST_BYTECODE)
  # A canonical temporary basename also accommodates platform-suffixed source fixture names.
  configure_file("${INK_SOURCE}" "${RunDirectory}/program.ink" COPYONLY)
  check_program_process(compile 0 "" "" "" --emit-bytecode "${RunDirectory}/program.inkobj" --module-root "${RunDirectory}" -i "${RunDirectory}/program.ink")
  check_program_process(link 0 "" "" "" --link-bytecode "${RunDirectory}/program.inkobj" --entry "program#main" -o "${RunDirectory}/program.inkbc")
  set(BytecodeError "${INK_EXPECTED_ERROR}")
  if(DEFINED INK_BYTECODE_ERROR AND NOT INK_BYTECODE_ERROR STREQUAL "")
    set(BytecodeError "${INK_BYTECODE_ERROR}")
  endif()
  check_program_process(bytecode "${INK_EXPECTED_STATUS}" "${INK_EXPECTED_STDOUT}" "${BytecodeError}" "${INK_EXPECTED_STDOUT_HEX}" --run-bytecode -i "${RunDirectory}/program.inkbc")
endif()
