if(NOT DEFINED INK_COMPILER OR NOT DEFINED INK_SOURCE OR NOT DEFINED INK_TEST_DIRECTORY OR NOT DEFINED INK_EXPECTED_STATUS OR NOT DEFINED INK_EXPECTED_STDOUT OR NOT DEFINED INK_EXPECTED_ERROR)
  message(FATAL_ERROR "Compiler, source, test directory and expected process results are required")
endif()

# Preserve raw stdout bytes while testing the real CLI's default main entry and diagnostics.
file(MAKE_DIRECTORY "${INK_TEST_DIRECTORY}")
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef RunId)
set(OutputFile "${INK_TEST_DIRECTORY}/source-program-${RunId}.stdout")
execute_process(COMMAND "${INK_COMPILER}" --interpret -i "${INK_SOURCE}" RESULT_VARIABLE Status OUTPUT_FILE "${OutputFile}" ERROR_VARIABLE Error TIMEOUT 15)
file(READ "${OutputFile}" Output)
if(NOT "${Status}" STREQUAL "${INK_EXPECTED_STATUS}")
  message(FATAL_ERROR "${INK_SOURCE}:main: expected exit ${INK_EXPECTED_STATUS}, got '${Status}'; stdout: ${Output}; stderr: ${Error}")
endif()

# The manifest uses | for newline; normalize the CRT's CRLF but assert all remaining bytes exactly.
string(REPLACE "|" "\n" ExpectedOutput "${INK_EXPECTED_STDOUT}")
string(REPLACE "\r\n" "\n" Output "${Output}")
if(NOT Output STREQUAL ExpectedOutput)
  message(FATAL_ERROR "${INK_SOURCE}:main: stdout differs; expected '${ExpectedOutput}', got '${Output}'")
endif()
if(DEFINED INK_EXPECTED_STDOUT_HEX AND NOT INK_EXPECTED_STDOUT_HEX STREQUAL "")
  file(READ "${OutputFile}" OutputHex HEX)
  string(TOLOWER "${INK_EXPECTED_STDOUT_HEX}" ExpectedOutputHex)
  if(NOT OutputHex STREQUAL ExpectedOutputHex)
    message(FATAL_ERROR "${INK_SOURCE}:main: stdout bytes differ; expected '${ExpectedOutputHex}', got '${OutputHex}'; file: ${OutputFile}")
  endif()
endif()
if(INK_EXPECTED_ERROR STREQUAL "")
  if(NOT Error STREQUAL "")
    message(FATAL_ERROR "${INK_SOURCE}:main: unexpected stderr: ${Error}")
  endif()
elseif(NOT Error MATCHES "${INK_EXPECTED_ERROR}")
  message(FATAL_ERROR "${INK_SOURCE}:main: expected diagnostic '${INK_EXPECTED_ERROR}', got: ${Error}")
endif()
file(REMOVE "${OutputFile}")
