#!/usr/bin/env python3
"""Generate the tokenizer's pinned Unicode 15.1 lookup tables.

The generated file is checked in so normal Ink builds do not depend on Python
or on the host Unicode database. Regenerate it with Python 3.13.
"""

from pathlib import Path
import sys
import unicodedata


EXPECTED_VERSION = "15.1.0"


def ranges(values):
    result = []
    start = previous = None
    for value in values:
        if start is None:
            start = previous = value
        elif value == previous + 1:
            previous = value
        else:
            result.append((start, previous))
            start = previous = value
    if start is not None:
        result.append((start, previous))
    return result


def canonical_decomposition(codepoint):
    raw = unicodedata.decomposition(chr(codepoint))
    if not raw or raw.startswith("<"):
        return []
    return [int(piece, 16) for piece in raw.split()]


def generated_text():
    xid_start = ranges(codepoint for codepoint in range(0x110000) if codepoint != 0x5F and chr(codepoint).isidentifier())
    xid_continue = ranges(codepoint for codepoint in range(0x110000) if codepoint != 0x5F and ("A" + chr(codepoint)).isidentifier())

    decomposition_values = []
    decomposition_entries = []
    composition_entries = []
    combining_entries = []
    for codepoint in range(0x110000):
        combining_class = unicodedata.combining(chr(codepoint))
        if combining_class:
            combining_entries.append((codepoint, combining_class))
        decomposition = canonical_decomposition(codepoint)
        if decomposition:
            decomposition_entries.append((codepoint, len(decomposition_values), len(decomposition)))
            decomposition_values.extend(decomposition)
            if len(decomposition) == 2 and unicodedata.normalize("NFC", "".join(chr(value) for value in decomposition)) == chr(codepoint):
                composition_entries.append(((decomposition[0] << 21) | decomposition[1], codepoint))

    lines = ["// Generated by src/tools/generate_unicode_data.py from Python's Unicode 15.1 database.", "// Do not edit this file manually.", ""]
    lines.append("constexpr CodePointRange kXidStartRanges[] = {")
    lines.extend(f"  {{0x{lower:X}, 0x{upper:X}}}," for lower, upper in xid_start)
    lines.append("};")
    lines.append("")
    lines.append("constexpr CodePointRange kXidContinueRanges[] = {")
    lines.extend(f"  {{0x{lower:X}, 0x{upper:X}}}," for lower, upper in xid_continue)
    lines.append("};")
    lines.append("")
    lines.append("constexpr char32_t kCanonicalDecompositionValues[] = {")
    for offset in range(0, len(decomposition_values), 12):
        lines.append("  " + ", ".join(f"0x{value:X}" for value in decomposition_values[offset:offset + 12]) + ",")
    lines.append("};")
    lines.append("")
    lines.append("constexpr DecompositionEntry kCanonicalDecompositions[] = {")
    lines.extend(f"  {{0x{codepoint:X}, {offset}, {length}}}," for codepoint, offset, length in decomposition_entries)
    lines.append("};")
    lines.append("")
    lines.append("constexpr CombiningClassEntry kCombiningClasses[] = {")
    lines.extend(f"  {{0x{codepoint:X}, {combining_class}}}," for codepoint, combining_class in combining_entries)
    lines.append("};")
    lines.append("")
    lines.append("constexpr CompositionEntry kCanonicalCompositions[] = {")
    lines.extend(f"  {{0x{key:X}ULL, 0x{codepoint:X}}}," for key, codepoint in sorted(composition_entries))
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def main():
    if unicodedata.unidata_version != EXPECTED_VERSION:
        raise SystemExit(f"expected Unicode {EXPECTED_VERSION}, got {unicodedata.unidata_version}")
    source_root = Path(__file__).resolve().parents[1]
    output = source_root / "lib" / "tokenizer" / "unicode_data.inc"
    output.write_text(generated_text(), encoding="utf-8", newline="\n")
    print(output)


if __name__ == "__main__":
    sys.exit(main())
